apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1-noprod1-service1
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io # Cancella i pod se cancelli la App
spec:
  project: default
  source:
    repoURL: 'https://github.com/giovannisciortino/acm_appset_app1.git'
    targetRevision: HEAD
    path: workloads/service1  # Punta al deployment reale
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: app1-noprod1   # Il namespace di destinazione richiesto
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true    # Crea il namespace app1-noprod1 se non esiste
